import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAllChatbotSessions } from '../../api/chatbotApi';
import ThemeToggle from '../../components/common/ThemeToggle';
import './TriageQueue.css';

function TriageQueue() {
    const navigate = useNavigate();
    const [sessions, setSessions] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchSessions();
        const interval = setInterval(fetchSessions, 30000); // 30s auto-refresh
        return () => clearInterval(interval);
    }, []);

    const fetchSessions = async () => {
        try {
            const data = await getAllChatbotSessions();
            setSessions(data || []);
        } catch (error) {
            console.error('Failed to fetch triage sessions:', error);
        } finally {
            setLoading(false);
        }
    };

    const formatDate = (dateString) => {
        const d = new Date(dateString);
        return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
    };

    return (
        <div className="aq-wrapper bg-[var(--background-light)] dark:bg-[var(--background-dark)] text-slate-800 dark:text-slate-100 flex flex-col h-screen w-full overflow-hidden">
            <div className="absolute top-4 right-4 z-50">
                <ThemeToggle />
            </div>

            <div className="aq-topbar border-b border-slate-200 dark:border-slate-800/50 bg-white/40 dark:bg-slate-900/40 backdrop-blur-md px-8 py-6 flex justify-between items-center z-10">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-indigo-600 to-purple-500 flex items-center justify-center text-white shadow-lg shadow-indigo-500/30">
                        <span className="material-symbols-outlined text-2xl">smart_toy</span>
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight text-slate-800 dark:text-white">AI Pre-Screening Queue</h1>
                        <p className="text-sm text-slate-500 dark:text-slate-400">Review patient SOAP summaries generated by the AI Triage Engine</p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <button onClick={fetchSessions} className="doctor-glass-button px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 hover:bg-white/50 dark:hover:bg-slate-800/50 transition border border-slate-200 dark:border-slate-700">
                        <span className="material-symbols-outlined text-sm">refresh</span>
                        Refresh
                    </button>
                    <button onClick={() => navigate('/doctor/dashboard')} className="doctor-glass-button px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 border border-slate-200 dark:border-slate-700 hover:bg-white/50 dark:hover:bg-slate-800/50 transition">
                        <span className="material-symbols-outlined text-sm">arrow_back</span>
                        Back to Dashboard
                    </button>
                </div>
            </div>

            <div className="flex-grow overflow-y-auto p-8">
                {loading ? (
                    <div className="flex items-center justify-center h-full">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
                    </div>
                ) : sessions.length === 0 ? (
                    <div className="flex flex-col items-center justify-center h-full text-center p-8">
                        <div className="w-20 h-20 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mb-4">
                            <span className="material-symbols-outlined text-4xl text-slate-400">inventory_2</span>
                        </div>
                        <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-2">No Active Triage Sessions</h3>
                        <p className="text-slate-500 dark:text-slate-400 max-w-sm">When patients complete the AI pre-screening, their SOAP summaries will appear here for your review.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {sessions.map(session => (
                            <div key={session.id} className="glass-card rounded-3xl p-6 transition-transform hover:-translate-y-1 hover:shadow-xl border border-white/20 dark:border-slate-700/50 relative overflow-hidden group border-l-4" style={{ borderLeftColor: session.priority === 'high' ? '#f43f5e' : session.priority === 'low' ? '#eab308' : '#6366f1' }}>
                                <div className="absolute top-0 right-0 p-4">
                                    <span className={`text-[10px] font-bold uppercase px-2 py-1 rounded-full ${session.status === 'completed' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>
                                        {session.status}
                                    </span>
                                </div>
                                <div className="mb-4 pr-16">
                                    <h4 className="text-lg font-bold text-slate-800 dark:text-white capitalize">{session.first_name || 'Unknown'} {session.last_name || 'Patient'}</h4>
                                    <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{formatDate(session.created_at)}</p>
                                </div>

                                {session.soap_summary ? (
                                    <div className="space-y-3 mb-6">
                                        <div className="bg-slate-50 dark:bg-slate-800/50 p-3 rounded-xl border border-slate-100 dark:border-slate-700/50">
                                            <span className="text-[10px] uppercase font-bold text-slate-400">Chief Complaint (S)</span>
                                            <p className="text-sm font-medium text-slate-800 dark:text-slate-200 mt-1 line-clamp-2">{session.soap_summary.subjective}</p>
                                        </div>
                                        <div className="flex gap-2">
                                            <div className="flex-1 bg-slate-50 dark:bg-slate-800/50 p-3 rounded-xl border border-slate-100 dark:border-slate-700/50">
                                                <span className="text-[10px] uppercase font-bold text-slate-400">Recommendation</span>
                                                <p className="text-sm font-semibold text-indigo-600 dark:text-indigo-400 mt-1 line-clamp-1 truncate">{session.recommended_department}</p>
                                            </div>
                                            <div className="bg-slate-50 dark:bg-slate-800/50 p-3 rounded-xl border border-slate-100 dark:border-slate-700/50 flex flex-col items-center justify-center min-w-[80px]">
                                                <span className="text-[10px] uppercase font-bold text-slate-400 text-center">Confidence</span>
                                                <span className={`text-sm font-bold mt-1 ${session.confidence_score >= 0.8 ? 'text-emerald-500' : session.confidence_score >= 0.6 ? 'text-amber-500' : 'text-rose-500'}`}>
                                                    {(session.confidence_score * 100).toFixed(0)}%
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="h-32 flex flex-col items-center justify-center bg-slate-50 dark:bg-slate-800/30 rounded-2xl border border-dashed border-slate-200 dark:border-slate-700 mb-6">
                                        <span className="material-symbols-outlined text-slate-300 dark:text-slate-600 mb-2">hourglass_empty</span>
                                        <p className="text-xs font-medium text-slate-500 dark:text-slate-400">Assessment in progress...</p>
                                    </div>
                                )}

                                <button
                                    onClick={() => alert('Detailed view and conversion to Clinical Note coming soon!')}
                                    className="w-full py-2.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-600 dark:bg-indigo-900/20 dark:hover:bg-indigo-900/40 dark:text-indigo-400 rounded-xl font-bold text-sm transition-colors border border-indigo-100 dark:border-indigo-500/20 flex items-center justify-center gap-2"
                                    disabled={!session.soap_summary}
                                >
                                    <span className="material-symbols-outlined text-lg">medical_information</span>
                                    {session.soap_summary ? 'View Full SOAP Note' : 'Awaiting Summary'}
                                </button>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}

export default TriageQueue;
